services:
  webapp:
    
    build: 
      context: ./webapp
      
    ports:
      - "8000:8000"
    networks:
      - frontend_network
      - backend_network

  pythoncompiler:
    build: 
      context: ./compiler_python
    expose:
      - "7999"
    networks:
      - backend_network
    volumes:
      - "./data/riddles/:/quiz:rw"

  db:
    build: 
      context: ./db
    ports:
      - "7998:7998"
    networks:
      - backend_network
    volumes:
      - "./data:/data:rw"

networks:
  frontend_network:
    driver: bridge
  
  backend_network:
    driver: bridge